language: python
addons:
  postgresql: "9.6"
python:
  - "3.6"
before_script:
  - cp environment-sample environment
  - git clone --depth=1 https://github.com/ebmdatalab/euctr-tracker-data.git ../euctr-tracker-data
script:
  - source environment && cd euctr && ./manage.py test --settings=euctr.settings
