language: python
services:
  - postgresql
python:
  - "3.6"
before_script:
  - cp environment-sample environment
script:
  - source environment && cd euctr && ./manage.py test frontend/tests --settings=euctr.settings
